repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        stages: [commit]
        # Optional: configure exclusions via .gitleaksignore if needed
        # args: ["--redact"]