[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SEO and Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets for better performance
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirects for SEO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific page redirects for better SEO
[[redirects]]
  from = "/pricing"
  to = "/#pricing"
  status = 301

[[redirects]]
  from = "/faq"
  to = "/#faq"
  status = 301

[[redirects]]
  from = "/meetings"
  to = "/#meetings"
  status = 301

[[redirects]]
  from = "/webinars"
  to = "/#webinars"
  status = 301

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "vite"


